kayttooikeus.tasks.export.enabled: false
kayttooikeus.tasks.export.bucket-name: oph-yleiskayttoiset-export-hahtuva
kayttooikeus.tasks.export.copy-to-lampi: false
kayttooikeus.tasks.export.lampi-bucket-name: none
kayttooikeus.tasks.export.lampi-role-arn: none
kayttooikeus.tasks.export.lampi-external-id: none
