sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: "bj9FkC0P3rba/8TCWmFwZyOgn5IjunC9CvQNVNZpg/3jSFTDIBZejOl0DN4uf8SDV1S188OS/RhnurrF+Yyf3ufUHllQsrWnujuG4GaGYp5A/DpyIykknAL7t7PMtRGIj008CCkxD3ttJX9DFCvAqthDPHu10CY89ft6gcjIIH00NjlYp+Id2DdC1HMHWze0BAtG71HhuMFIE30C3jIdKVHtP7W44BKhbtex6TudMHNvWYkEGZchxJdgtrzlnakXZtyJzVcjLq4uBgbd4DIgq3jrsixyd2Oz4rygAyzzmNFxnYE0xRpP/dioocAzhDKv//RSCmNDLRQFl5SyauRp7Hld7gQMvxZtQT53eK6Nfz+5qqEnkzVpZyakhT30icRGyFGOUnH1eYzQG0nlAHTxffnexQx4YW1aypmsKO0VrX0JcUxK5fLlFw0erjpUCxEC1Qpd/lb8jKdvQa46X5GOkjWyagUfXyQkrWt1QnZMvacUzDNj05BopFZdbWZT1KVUVi04uD5Tf0nEun60Amqn1Kd77R8kDeX+X2FhqzKJIsqObHgEFe1Co//eKA3ommK4hedetwT7f3dqbRIDhc3MFuQ6slta5snT3lh3qG2WpMEWL590UN9hvca/BfAZRXbd/qONK2gzA4fDV5TmYgpnWCJvroYfA+j6hyot7U7EyFs="
    # ARTIFACTORY_PASSWORD
    - secure: "NnhMSPjD3+73UBnJ/sveaMk+Q/VztecfEuCwZVtH9HNuqyNYQb9cHy1yDytIgvzfalK+6ZUq2fjDnYHBEkkg7V1RdlcPR9RjnPAF7WkcukmzPNA3aucNDyjoAVNbf3gF58NsIw3D+K9KtuIlvinCjO9hVa6kv9AaT5xXPRNxjZY0yxwdBXpmNlaVlk6gJ6bJ1dCsq5lqSRgEfIB4s47Yl1L9NqkMKXq4uWvM1phMlQ1npvB9F+QDpjAin5u3XYSw2rnnNrIt3WiT5VJiEAAO9WPg0bt+PuTZIETu+u3C1MpRS98nl1cRpMMfsqXWysUzxeuWCQ0nRxDoNPeiWdg2tl5IaBwdcH1fRSXgpRMwFHqOPwLdS1l3M/aWhdTBnCFhFUAJd7Cd8C1Y/HZM1IWcQ3f4m7cE0YY8vWMTtxnHnEfpSDS9WpC7QK4BJJTG2vkqMMvcSv+kgrf6nxLWMc3DRhrG82tt+HIuY4oU5fgTgX77eMdzAkvInZkHaRLzKxk8/ogPsF7O0zqLch87dO8dL6QcB8k5ZqnlRT+BDEg0wUPwBjjh4PdPNDAERndG2IjvNTWfkZxSQHtyPSCpuwweX7opSsrAo+7RIWEGtvRz4mlP82+pMWFEi68MKw3T3hPLg9DmWerAk68bB8Tbs2EsDncA1UdCUMIZTfF9bPaRFy4="
    # AWS_ACCESS_KEY_ID
    - secure: "Q2qNr3f4hJ7dIjuwIr+ScWF97U+MvZqz7IoeWwCWBJxBd1iywY2W2ypP1GrgAZobWSmq349ov2HsMiLeAc5Y3yCuD5yzs9qSyOXSs4kKi5smv5m0EGR4xp9LG84NOxIFLjzMP6NT35Ys7upmr0fRX33KtNF16txUMZ/QgdfUxw+pJOEPprWjzjqXTydctSusCZ0Lm8EaR5gry5WW1BODsNcaTW6uuO1MOQxekSIocSnmxVYeflaUtiAmQYDYpCrAEyX/zjz3oDNYqd+HF8p3TXesp212w6VuK81wY7JM7/3QiO5QVLPQB+dofNhdTtoQkWb5Ns3ihEnieNGk8RaZrJMb9G7T2aPXZu+/AiC7e2P7LJHHD2XqaLaSDkx+pqG3/QcvHRA/UzOvbp3LFxs44AGBqNUGJpLhqmg4BQRor0SsQULLmtY/kmuQs4Y9pEOyF04BXgkSnygUdMsjTqYC/GzvFE+Esr4toN/1xYJGJc4M9FjmvLCpEct7X6uCvLtOK/rOflB2GETGyFgmB9Zr3ucyQMr4s/HsWsgPIznItLEYwCekxYvVOMoWZOnUAA6v3Ut7CVTeCGMQVyWXSbY28SDM3Jw4+0Y7029+CcHOJINMR2k+WwiaAseczya+gRGdQhAmZ7ZduJ6CO+o0BdBXXu58Xk5xHNS50+SPRp8gPLU="
    # AWS_SECRET_ACCESS_KEY
    - secure: "KLaKEDNgFMnE8DqmeoML75sa1knq1xUXYmpovXNoS0WWrDqpOplTTEIwslN385OiqgNxAql1rorEZoQPKnQZ/+WsYQKH5Xl1Vg+sZ1BHiMorzW+2m9rpGWyND6wROov+HDIZ6z6vWNPDkVVRo0NUyqdaUvx89OBgVLbQHiyaaF7nnh9bCHskOBXR6LpUAhaGhR5gyeCMNtomZmvYaH9EF8jylFDdF5M/NLar3D6+7i6kGmiGwLmN5y4fxJ6dF4RKUZfbtCanlSOYNl0Jw4oMERsxx5/sxeCppOZt01BJiLTVcEnqRGd0ZeYm5acP6o8y4h3Bi/2njzEkjmBi8e8V918VaurK9RGcMmcV+mf2KkAwhbcRo5pruFq07GnXgzfcrgevtx35N4jNHh5qZVGIyDBmEnvauWiKEyi091Pqd8mB6n6Zol/eMczVv/0+TRNnB4XkCYmrdINBN7WVMxl2vqJtGABXU149cWO8u3W9GYKfrSW6giMDyFKisXojOMp70cpP+kxiZ87Sf72GTK1vhT8ARgdo+vVYpW6C7ywjZMwHxaVoIUJZWt/kecwkWFUZGOMZTAOawqyj/OOr1fGj/ImlFUKwyo/m2xkR+z223ZlqTRi888CHQgiplmEZui1lc3O9GDd2G/OoQEvu3F0x6oB7L4PMXQbSpieNsLcaKCk="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="kayttooikeus"

script:
  - mvn -P ci clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv kayttooikeus-service/target/kayttooikeus-service-*SNAPSHOT.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script: mvn deploy -pl kayttooikeus-api -am -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true
