logging.level.org:
  springframework.web: info
  hibernate: info

spring:
  mandatory-file-encoding: UTF-8
  profiles.active: default

server:
  context-path: /kayttooikeus-service
  session:
    tracking-modes: cookie
    timeout: 30

