logging.level.org:
  springframework.web: info
  hibernate: info

spring:
  mandatory-file-encoding: UTF-8
  profiles.active: default

server:
  servlet:
    context-path: /kayttooikeus-service
    session:
      timeout: 30s
    tracking-modes:
      - cookie
