logging.level.org:
  springframework.web: info
  hibernate: info

spring:
  mandatory-file-encoding: UTF-8
  profiles.active: default

server:
  context-path: /kayttooikeus-service
  session:
    tracking-modes: cookie
    timeout: 30

kayttooikeus:
  scheduling:
    enabled: false
    configuration:
      organisaatiocache: "0 0 0 * * ?"
      vanhentuneetkayttooikeudet: 0 0 3 * * ?
      kayttooikeusmuistutus: "0 30 4 * * ?"
