name: kayttooikeus
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.4
        ports:
          - 5437:5432
        env:
          POSTGRES_USER: app
          POSTGRES_DB: kayttooikeus
          POSTGRES_PASSWORD: kayttooikeus
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "maven"
      - name: Maven version
        run: mvn --version
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean install -B -Dbranch=$GITHUB_REF_NAME -Drevision=$GITHUB_SHA -DbuildNumber=$GITHUB_RUN_NUMBER/$GITHUB_RUN_ATTEMPT org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Opetushallitus_kayttooikeus
      - name: Upload kayttooikeus-jar
        uses: actions/upload-artifact@v4
        with:
          name: kayttooikeus-jar
          path: kayttooikeus-service/target/kayttooikeus-service-*SNAPSHOT.jar
  deploy-container:
    needs: [build]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: kayttooikeus
      base-image: baseimage-fatjar-openjdk21:master
      configfolder: src/main/resources/oph-configuration
      jarfile: kayttooikeus-service-*SNAPSHOT
      jarfolder: .
      download-artifact: true
      download-artifact-name: kayttooikeus-jar
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
  deploy-artifacts:
    needs: [ build ]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'
      - name: Maven version
        run: mvn --version
      - name: Deploy
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          mvn deploy -pl fi.vm.sade.kayttooikeus:kayttooikeus-api -am -DskipTests --settings ci-tools/common/maven-settings.xml

